# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_crypto"
version = "0.21.1"
edition = "2018"
description = "Web Cryptography API implementation for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.88.1", path = "../../core" }
deno_web = { version = "0.38.1", path = "../web" }
rand = "0.8.3"
uuid = { version = "0.8.2", features = ["v4"] }
