# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_crypto"
version = "0.24.1"
edition = "2018"
description = "Web Cryptography API implementation for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.92.0", path = "../../core" }
deno_web = { version = "0.41.1", path = "../web" }
tokio = { version = "1.8.0", features = ["full"] }
rand = "0.8.3"
ring = { version = "0.16.20", features = ["std"] }
rsa = "0.4.0" # TODO: remove "pem" feature when next release is on crates.io
sha-1 = "0.9.6"
sha2 = "0.9.5"
serde = { version = "1.0.123", features = ["derive"] }
uuid = { version = "0.8.2", features = ["v4"] }
lazy_static = "1.4.0"
num-traits = "0.2.14"