# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_console"
version = "0.51.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Implementation of Console API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.133.0", path = "../../core" }
