# Copyright 2018-2019 the Deno authors. All rights reserved. MIT license.
sudo: false
language: rust
rust:
  - 1.37.0
git:
  depth: 1
env:
  global:
  - RUST_BACKTRACE=full
  - PATH=$TRAVIS_BUILD_DIR/third_party/llvm-build/Release+Asserts/bin:$PATH
  - PYTHONPATH=third_party/python_packages
  - SCCACHE_BUCKET=deno-sccache
  - AWS_ACCESS_KEY_ID=AKIAIVRN52PLDBP55LBQ
  # AWS_SECRET_ACCESS_KEY=...
  - secure: "ugSLNiUOQs53Oyy78EQyr2bu+//uoskbuoucenUUHM5I11M15yq1XuBJ26fIK1Jatza9pOGJNI8+4dSMWZW1GMFqgOZTKXv4kZFqU915/L1gsfS2bljB8pD1Qoq68ieGCQ49vBSFOWP24gtWBfKVJqU3HGHJgA5Ia/ujW3e37jr20xGqaBEcTjgin2fjm7VTao+hOOAMf47YkZNTEuLEHVPbDZM2tCCSlUdLpdyPB6mzX7XVmRxO26mtaHEeecivtaS6xXJXmns7OkntOzwgJi46B5uMgZz42UZ9qy1fCq8yCOyADb/Hu2WaJm7MIehHVhdC/siRzUUSOJ4N9gOPaFFAy5D28sDEa/IvlVriOwXirmDdPSlkTpwZ1NiisZXdZMaK6CWroaCHv9hYrJ7wKcntLQjLnnnskcyqxIVC7uEdlKHyLTNziyxol6oU/2Ym1NDoYWPDzcIeCkCr+xBapLXTVcg60YvcL/h+6wy5rp1v2h9R5B8HCCvmyc2X/FyaAmi8P7DYYHQL8+g+B0nGmzrrSGJzsEL7vChyiKfeNG7nnJKrU1+V8/+bPGsuPOK1XDTx80Uq56EzjHUPXy59zqtYL7ZZAIL0BQPxgm43yUCJfYSIKiwB9Odu+vb2DLDk5CLi45OHh2K7yi9m/lxlXla945az5OYO2l7a5m7rWF8="
cache:
  cargo: true
  directories:
  - prebuilt/mac
  - prebuilt/linux64
  - third_party/v8/build/linux/debian_sid_amd64-sysroot/
  - third_party/v8/buildtools/mac/
  - third_party/v8/buildtools/linux64/
  - third_party/v8/third_party/llvm-build/

install:
# Because prebuilt/ is cached, we need to manually reset changes that might
# happen to the sha1 files here.
- git checkout -- prebuilt
- nvm install v12
- nvm use --delete-prefix v12
- node -v
- rustup component add rustfmt
- rustc --version
- cargo --version
- |-
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export PATH="`pwd`/prebuilt/mac:$PATH"
  else
    export PATH="`pwd`/prebuilt/linux64:$PATH"
  fi

before_script:
# Need to run setup.py in order to download clang-format binary, needed for
# test_format.py.
- ./tools/setup.py
# Start sccache, then throw away the S3 access key.
- sccache --start-server
- unset AWS_SECRET_ACCESS_KEY
- set -e
- ./tools/lint.py
- ./tools/test_format.py

# Default script for release builds.
script:
- cargo build -vv --release --locked --all-targets
- cargo test -vv --release --all-targets --locked
# For some reason it's faster to run clippy after build.
- rustup component add clippy
- cargo clippy --all-targets --release --locked -- -D clippy::all

jobs:
  fast_finish: true
  include:
    - name: "release mac x86_64"
      os: osx
      osx_image: xcode11
      after_success:
        - &gzip_release
          gzip -c target/release/deno > target/release/deno_${TRAVIS_OS_NAME}_x64.gz
      deploy:
      - &release_provider
        provider: releases
        api_key: &github-token
          secure: RIwv515oDcPAlEvt7uG8FeSFi6Tz6ODJUOXcFj6FYUPszxJ7Cg1kBLKln+fNW5OeOc52VsaZb/vPZ85skyEM6zk2ijL9FcSnnfNEm548w77iH6G0sk09NgBTy6KRXES6NZHD9jN1YTWYkT2G1NQi7mLqxR8a8pnWTbeK5HhtSWGsZPtXqf5iQbvnWsmKA0/w+FIgKupU0xe/qsYjh0eMLYpZDUWoKO0VxBKJ/ix5Uz91aJTjMIcHHij+ALg4pk+FkDotdyx39XB9b25KDxGuaI7NxWjSPzDxs/ZBHP6QYDLO0ti93ftvLAxRoBKPFoZrXqAu3KG9anr9WvxE40DO9OdV0VX2ZUatMUQm3DpSheN8ml2sErFqjIInqlpkdOVDYORz7FikPxkb9DKt+iuyFfxPRa4YWJv2tg8+Hy/nRCQw69OoKqrSNJ8KJDB3OjYbRBtdHz79RLJhTsGZla6RiyXfM7crR7CbFjbwdbW3Pt60t24fhvXQ0SwR0QTgzS/ieYEQHq/9GtSQA/Tn4kdIkyN6BdOMrQd/aUtgKmNdqbSlfmWGNyNZIxHdB+3RrTNT1tagkRI4UHEUfEujpIdYKwLjv0Xmi/VtTM+zOSkzHsIWGPfHBmIGnXfAItUHqivQYJ15E+dzg3T1CEbBxkDQtvwien9Fa8/pBsMkyovl8ps=
        file: "target/release/deno_${TRAVIS_OS_NAME}_x64.gz"
        on:
          tags: true
          repo: denoland/deno
        skip-cleanup: true

    - name: "release linux x86_64"
      os: linux
      after_success:
        - *gzip_release
      deploy:
      - *release_provider

    # Run benchmarks and publish the result to github pages.
    - name: "benchmarks"
      script:
        - cargo build -vv --release --locked --all-targets
        - ./tools/benchmark.py target/release && cp -r website/* gh-pages/
      deploy:
      - provider: pages
        github-token: *github-token
        keep-history: true
        local-dir: gh-pages
        on:
          branch: master
          repo: denoland/deno
        skip-cleanup: true
