variables:
  DENO_VERSION: 'v0.3.1'

jobs:

- job: 'Linux'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: curl -L https://deno.land/x/install/install.sh | sh -s $(DENO_VERSION)
  - script: echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - script: deno test.ts --allow-run --allow-net --allow-write --allow-read
  - script: deno format.ts --allow-run --allow-write --allow-read --check

- job: 'Mac'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: curl -L https://deno.land/x/install/install.sh | sh -s $(DENO_VERSION)
  - script: echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - script: deno test.ts --allow-run --allow-net --allow-write --allow-read
  - script: deno format.ts --allow-run --allow-write --allow-read --check

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: iwr https://deno.land/x/install/install.ps1 -out install.ps1; .\install.ps1 $(DENO_VERSION)
  - bash: echo "##vso[task.prependpath]C:\Users\VssAdministrator\.deno\\bin"
  - bash: deno.exe test.ts --allow-run --allow-net --allow-write --allow-read
  - bash: deno.exe format.ts --allow-run --allow-write --allow-read --check
