# Dummy package info required by `cargo fetch`.
# Use tools/sync_third_party.py to install deps after editing this file.
# Deno does not build with cargo. Deno uses a build system called gn.
# See build_extra/rust/BUILD.gn for the manually built configuration of rust
# crates.
[package]
name = "deno"
version = "0.0.0"

[dependencies]
dirs = "1.0.3"
flatbuffers = { path = "third_party/flatbuffers/rust/flatbuffers/" }
futures = "0.1.23"
hyper = "0.12.9"
# The current version of hyper-rustls, 0.14.0, depends on tokio-core, which is
# deprecated.
hyper-rustls = { git = "https://github.com/ctz/hyper-rustls.git" }
libc = "0.2.42"
log = "0.4.4"
rand = "0.4.3"
ring = "0.13.2"
tempfile = "3"
tokio = "0.1.8"
url = "1.7.1"
