# Copyright 2018 the Deno authors. All rights reserved. MIT license.
# Dummy package info required by `cargo fetch`.
# Use tools/sync_third_party.py to install deps after editing this file.
# Deno does not build with cargo. Deno uses a build system called gn.
# See build_extra/rust/BUILD.gn for the manually built configuration of rust
# crates.
[package]
name = "deno"
version = "0.2.8"
edition = "2018"

[dependencies]
atty = "0.2.11"
dirs = "1.0.4"
flatbuffers = "0.5.0"
futures = "0.1.25"
getopts = "0.2.18"
http = "0.1.14"
hyper = "0.12.20"
hyper-rustls = "0.15.0"
lazy_static = "1.2.0"
libc = "0.2.46"
log = "0.4.6"
rand = "0.6.4"
remove_dir_all = "0.5.1"
ring = "0.13.5"
rustyline = "3.0.0"
serde_json = "1.0.35"
source-map-mappings = "0.5.0"
tempfile = "3.0.5"
tokio = "0.1.14"
tokio-executor = "0.1.6"
tokio-fs = "0.1.5"
tokio-io = "0.1.11"
tokio-process = "0.2.3"
tokio-threadpool = "0.1.10"
url = "1.7.2"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.6"
