# Dummy package info required by `cargo fetch`.
# Use tools/sync_third_party.py to install deps after editing this file.
# Deno does not build with cargo. Deno uses a build system called gn.
# See build_extra/rust/BUILD.gn for the manually built configuration of rust
# crates.
[package]
name = "deno"
version = "0.0.0"

[dependencies]
url = "1.7.1"
libc = "0.2.42"
log = "0.4.3"
rand = "0.4.2"
tempfile = "3"
tokio = "0.1"
hyper = "0.12.8"
hyper-rustls = "0.14.0"
flatbuffers = { path = "third_party/flatbuffers/rust/flatbuffers/" }

