[workspace]
members = [
  "cli",
  "core",
  "test_plugin",
  "test_util",
  "op_crates/web",
]
exclude = [
  "std/hash/_wasm"
]


[profile.release]
codegen-units = 1
lto = true
opt-level = 'z' # Optimize for size
