# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[workspace]
members = [
  "cli",
  "core",
  "runtime",
  "test_plugin",
  "test_util",
  "op_crates/fetch",
  "op_crates/web",
  "op_crates/crypto"
]
exclude = [
  "std/hash/_wasm"
]


[profile.release]
codegen-units = 1
lto = true
opt-level = 'z' # Optimize for size

[profile.bench]
codegen-units = 1
lto = true
opt-level = 'z' # Optimize for size

# Optimize these packages for perf
[profile.release.package.rand]
opt-level = 3
[profile.release.package.flate2]
opt-level = 3
[profile.release.package.brotli]
opt-level = 3
[profile.release.package.miniz_oxide]
opt-level = 3
[profile.release.package.async-compression]
opt-level = 3
[profile.release.package.brotli-decompressor]
opt-level = 3