# Dummy package info required by `cargo fetch`.
# Use tools/sync_third_party.py to install deps after editing this file.
# Deno does not build with cargo. Deno uses a build system called gn.
# See build_extra/rust/BUILD.gn for the manually built configuration of rust
# crates.
[package]
name = "deno"
version = "0.0.0"

[dependencies]
url = "1.7.1"
libc = "0.2.42"
log = "0.4.3"
sha1 = "0.6.0"
tempfile = "3"
tokio = {git = "https://github.com/tokio-rs/tokio.git", rev = "5d0d2a2e1214f856993df6965825c89bfcaa879e"}
hyper = "0.12.8"
crossbeam-deque = "= 0.5.1"
crossbeam-epoch = "= 0.5.1"
futures-core = "0.2.1"
