# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_url"
version = "0.7.0"
edition = "2018"
description = "URL API implementation for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.88.0", path = "../../core" }
idna = "0.2.3"
percent-encoding = "2.1.0"
serde = { version = "1.0.125", features = ["derive"] }

[dev-dependencies]
deno_bench_util = { version = "0.1.0", path = "../../bench_util" }

[[bench]]
name = "url_ops"
harness = false
