# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_ffi"
version = "0.3.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Dynamic library ffi for deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.98.0", path = "../../core" }
dlopen = "0.1.8"
libffi = { version = "=0.0.7", package = "deno-libffi" }
serde = { version = "1.0.125", features = ["derive"] }
