# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_runtime"
version = "0.1.0"
license = "MIT"
authors = ["the Deno authors"]
edition = "2018"
description = "Provides the deno runtime library"
repository = "https://github.com/denoland/deno"

[lib]
name = "deno_runtime"
path = "lib.rs"

[[example]]
name = "hello_runtime"
path = "examples/hello_runtime.rs"

[build-dependencies]
deno_core = { path = "../core", version = "0.71.0" }
deno_crypto = { path = "../op_crates/crypto", version = "0.5.0" }
deno_web = { path = "../op_crates/web", version = "0.22.0" }
deno_fetch = { path = "../op_crates/fetch", version = "0.14.0" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = "0.3.9"

[dependencies]
deno_core = { path = "../core", version = "0.71.0" }
deno_crypto = { path = "../op_crates/crypto", version = "0.5.0" }
deno_fetch = { path = "../op_crates/fetch", version = "0.14.0" }
deno_web = { path = "../op_crates/web", version = "0.22.0" }

atty = "0.2.14"
dlopen = "0.1.8"
encoding_rs = "0.8.24"
env_logger = "0.7.1"
filetime = "0.2.12"
http = "0.2.1"
indexmap = "1.6.0"
lazy_static = "1.4.0"
libc = "0.2.77"
log = "0.4.11"
notify = "5.0.0-pre.3"
percent-encoding = "2.1.0"
regex = "1.3.9"
ring = "0.16.19"
rustyline = { version = "7.0.0", default-features = false }
rustyline-derive = "0.4.0"
serde = { version = "1.0.116", features = ["derive"] }
shell-escape = "0.1.5"
sys-info = "0.7.0"
termcolor = "1.1.0"
tokio = { version = "0.2.22", features = ["full"] }
tokio-rustls = "0.14.1"
# Keep in-sync with warp.
tokio-tungstenite = "0.11.0"
uuid = { version = "0.8.1", features = ["v4"] }
warp = { version = "0.2.5", features = ["tls"] }
webpki = "0.21.3"
webpki-roots = "=0.19.0" # Pinned to v0.19.0 to match 'reqwest'.

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }
fwdansi = "1.1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.19.0"

[dev-dependencies]
# Used in benchmark
test_util = { path = "../test_util" }
