# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_runtime"
version = "0.84.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
repository = "https://github.com/denoland/deno"
description = "Provides the deno runtime library"

[features]
# "fake" feature that allows to generate docs on docs.rs
docsrs = []

[lib]
name = "deno_runtime"
path = "lib.rs"

[[example]]
name = "hello_runtime"
path = "examples/hello_runtime.rs"

[build-dependencies]
deno_broadcast_channel = { version = "0.70.0", path = "../ext/broadcast_channel" }
deno_cache = { version = "0.8.0", path = "../ext/cache" }
deno_console = { version = "0.76.0", path = "../ext/console" }
deno_core = { version = "0.158.0", path = "../core" }
deno_crypto = { version = "0.90.0", path = "../ext/crypto" }
deno_fetch = { version = "0.99.0", path = "../ext/fetch" }
deno_ffi = { version = "0.63.0", path = "../ext/ffi" }
deno_flash = { version = "0.12.0", path = "../ext/flash" }
deno_http = { version = "0.70.0", path = "../ext/http" }
deno_net = { version = "0.68.0", path = "../ext/net" }
deno_node = { version = "0.13.0", path = "../ext/node" }
deno_tls = { version = "0.63.0", path = "../ext/tls" }
deno_url = { version = "0.76.0", path = "../ext/url" }
deno_web = { version = "0.107.0", path = "../ext/web" }
deno_webgpu = { version = "0.77.0", path = "../ext/webgpu" }
deno_webidl = { version = "0.76.0", path = "../ext/webidl" }
deno_websocket = { version = "0.81.0", path = "../ext/websocket" }
deno_webstorage = { version = "0.71.0", path = "../ext/webstorage" }
deno_napi = { version = "0.6.0", path = "../ext/napi" }

lzzzz = '1.0'

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = "0.3.9"

[dependencies]
deno_broadcast_channel = { version = "0.70.0", path = "../ext/broadcast_channel" }
deno_cache = { version = "0.8.0", path = "../ext/cache" }
deno_console = { version = "0.76.0", path = "../ext/console" }
deno_core = { version = "0.158.0", path = "../core" }
deno_crypto = { version = "0.90.0", path = "../ext/crypto" }
deno_fetch = { version = "0.99.0", path = "../ext/fetch" }
deno_ffi = { version = "0.63.0", path = "../ext/ffi" }
deno_flash = { version = "0.12.0", path = "../ext/flash" }
deno_http = { version = "0.70.0", path = "../ext/http" }
deno_napi = { version = "0.6.0", path = "../ext/napi" }
deno_net = { version = "0.68.0", path = "../ext/net" }
deno_node = { version = "0.13.0", path = "../ext/node" }
deno_tls = { version = "0.63.0", path = "../ext/tls" }
deno_url = { version = "0.76.0", path = "../ext/url" }
deno_web = { version = "0.107.0", path = "../ext/web" }
deno_webgpu = { version = "0.77.0", path = "../ext/webgpu" }
deno_webidl = { version = "0.76.0", path = "../ext/webidl" }
deno_websocket = { version = "0.81.0", path = "../ext/websocket" }
deno_webstorage = { version = "0.71.0", path = "../ext/webstorage" }

atty = "0.2.14"
dlopen = "0.1.8"
encoding_rs = "0.8.31"
filetime = "0.2.16"
fs3 = "0.5.0"
http = "0.2.6"
hyper = { version = "0.14.18", features = ["server", "stream", "http1", "http2", "runtime"] }
libc = "0.2.126"
log = "0.4.16"
lzzzz = '1.0'
netif = "0.1.6"
notify = "5.0"
once_cell = "1.10.0"
regex = "1.6.0"
ring = "0.16.20"
serde = { version = "1.0.136", features = ["derive"] }
signal-hook-registry = "1.4.0"
termcolor = "1.1.3"
tokio = { version = "1.21", features = ["full"] }
uuid = { version = "1.0.0", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
fwdansi = "1.1.0"
winapi = { version = "0.3.9", features = ["commapi", "knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }
ntapi = "0.4.0"

[target.'cfg(unix)'.dependencies]
nix = "=0.24.2"

[dev-dependencies]
# Used in benchmark
test_util = { path = "../test_util" }

[package.metadata.docs.rs]
features = ["docsrs"]
