[package]
name = "deno_typescript"
version = "0.0.3"
license = "MIT"
description = "To compile TypeScript to a snapshot during build.rs"
repository = "https://github.com/ry/deno_typescript"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
deno = { path = "../core" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
