[package]
name = "deno_typescript"
version = "0.19.0"
license = "MIT"
description = "To compile TypeScript to a snapshot during build.rs"
repository = "https://github.com/ry/deno_typescript"
authors = ["the Deno authors"]
edition = "2018"

exclude = [
  "typescript/tests/*",
  "typescript/src/*",
  "typescript/scripts/*",
  "typescript/doc/*",
  "typescript/lib/*/*.json",
]

[lib]
path = "lib.rs"

[dependencies]
deno = { path = "../core", version = "0.19.0" }
serde_json = "1.0.40"
serde = { version = "1.0.100", features = ["derive"] }
