# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_lockfile"
version = "0.5.0"
edition = "2021"
license = "MIT"
description = "An implementation of a lockfile used in Deno"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
ring.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
test_util.workspace = true
