# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "1.13.2"
authors = ["the Deno authors"]
default-run = "deno"
edition = "2018"
license = "MIT"
repository = "https://github.com/denoland/deno"
description = "Provides the deno executable"

[[bin]]
name = "deno"
path = "main.rs"

[[bench]]
name = "deno_bench"
harness = false
path = "./bench/main.rs"

[build-dependencies]
deno_broadcast_channel = { version = "0.10.0", path = "../ext/broadcast_channel" }
deno_console = { version = "0.16.0", path = "../ext/console" }
deno_core = { version = "0.98.0", path = "../core" }
deno_crypto = { version = "0.30.0", path = "../ext/crypto" }
deno_fetch = { version = "0.39.0", path = "../ext/fetch" }
deno_ffi = { version = "0.3.0", path = "../ext/ffi" }
deno_http = { version = "0.7.0", path = "../ext/http" }
deno_net = { version = "0.7.0", path = "../ext/net" }
deno_timers = { version = "0.14.0", path = "../ext/timers" }
deno_url = { version = "0.16.0", path = "../ext/url" }
deno_web = { version = "0.47.0", path = "../ext/web" }
deno_webgpu = { version = "0.17.0", path = "../ext/webgpu" }
deno_webidl = { version = "0.16.0", path = "../ext/webidl" }
deno_websocket = { version = "0.21.0", path = "../ext/websocket" }
deno_webstorage = { version = "0.11.0", path = "../ext/webstorage" }
regex = "1.4.3"
serde = { version = "1.0.125", features = ["derive"] }

[target.'cfg(windows)'.build-dependencies]
winapi = "0.3.9"
winres = "0.1.11"

[dependencies]
deno_core = { version = "0.98.0", path = "../core" }
deno_doc = "0.10.0"
deno_lint = "0.12.0"
deno_runtime = { version = "0.24.0", path = "../runtime" }
deno_tls = { version = "0.3.0", path = "../ext/tls" }

atty = "0.2.14"
base64 = "0.13.0"
byteorder = "1.4.3"
clap = "2.33.3"
data-url = "0.1.0"
dissimilar = "1.0.2"
dprint-plugin-json = "0.12.3"
dprint-plugin-markdown = "0.9.4"
dprint-plugin-typescript = "0.50.2"
encoding_rs = "0.8.28"
env_logger = "0.8.4"
fancy-regex = "0.5.0"
filetime = "0.2.14"
http = "0.2.4"
# TODO(lucacasonato): unlock when https://github.com/tkaitchuck/aHash/issues/95 is resolved
indexmap = { version = "=1.6.2", features = ["serde"] }
jsonc-parser = { version = "0.17.0", features = ["serde"] }
lazy_static = "1.4.0"
libc = "0.2.98"
log = { version = "0.4.14", features = ["serde"] }
lspower = "1.1.0"
notify = "5.0.0-pre.10"
num_cpus = "1.13.0"
percent-encoding = "2.1.0"
pin-project = "1.0.7"
rand = { version = "0.8.4", features = ["small_rng"] }
regex = "1.4.3"
ring = "0.16.20"
rustyline = { version = "8.2.0", default-features = false }
rustyline-derive = "0.4.0"
semver-parser = "0.10.2"
serde = { version = "1.0.126", features = ["derive"] }
shell-escape = "0.1.5"
sourcemap = "6.0.1"
swc_bundler = "0.50.0"
swc_common = { version = "0.11.4", features = ["sourcemap"] }
swc_ecmascript = { version = "0.52.1", features = ["codegen", "dep_graph", "parser", "proposal", "react", "transforms", "typescript", "visit"] }
tempfile = "3.2.0"
termcolor = "1.1.2"
text-size = "1.1.0"
tokio = { version = "1.8.1", features = ["full"] }
tokio-rustls = "0.22.0"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
walkdir = "2.3.2"

[target.'cfg(windows)'.dependencies]
fwdansi = "1.1.0"
winapi = { version = "0.3.9", features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }

[dev-dependencies]
# Used in benchmark
chrono = "0.4.19"
flaky_test = "0.1.0"
os_pipe = "0.9.2"
test_util = { path = "../test_util" }
tower-test = "0.4.0"
trust-dns-client = "0.20.3"
trust-dns-server = "0.20.3"

[target.'cfg(unix)'.dev-dependencies]
exec = "0.3.1" # Used in test_raw_tty
nix = "0.20.0"

[package.metadata.winres]
# This section defines the metadata that appears in the deno.exe PE header.
OriginalFilename = "deno.exe"
LegalCopyright = "© Deno contributors & Deno Land Inc. MIT licensed."
ProductName = "Deno"
FileDescription = "Deno: A secure runtime for JavaScript and TypeScript"
