# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "1.9.1"
license = "MIT"
authors = ["the Deno authors"]
edition = "2018"
description = "Provides the deno executable"
repository = "https://github.com/denoland/deno"
default-run = "deno"

[[bin]]
name = "deno"
path = "main.rs"

[[bin]]
name = "denort"
path = "main_runtime.rs"

[[bench]]
name = "deno_bench"
harness = false
path = "./bench/main.rs"

[build-dependencies]
deno_core = { path = "../core", version = "0.85.0" }
deno_runtime = { path = "../runtime", version = "0.12.0" }
regex = "1.4.3"
serde = { version = "1.0.125", features = ["derive"] }

[target.'cfg(windows)'.build-dependencies]
winapi = "0.3.9"
winres = "0.1.11"

[dependencies]
deno_core = { path = "../core", version = "0.85.0" }
deno_doc = "0.3.0"
deno_lint = "0.4.0"
deno_runtime = { path = "../runtime", version = "0.12.0" }

atty = "0.2.14"
base64 = "0.13.0"
byteorder = "1.4.3"
clap = "2.33.3"
dissimilar = "1.0.2"
dprint-plugin-json = "0.10.1"
dprint-plugin-markdown = "0.6.2"
dprint-plugin-typescript = "0.44.0"
encoding_rs = "0.8.28"
env_logger = "0.8.3"
fancy-regex = "0.5.0"
filetime = "0.2.14"
http = "0.2.3"
indexmap = { version = "1.6.2", features = ["serde"] }
jsonc-parser = { version = "0.17.0", features = ["serde"] }
lazy_static = "1.4.0"
libc = "0.2.93"
log = { version = "0.4.14", features = ["serde"] }
lspower = "1.0.0"
notify = "5.0.0-pre.7"
percent-encoding = "2.1.0"
pin-project = "1.0.6"
regex = "1.4.3"
ring = "0.16.20"
rustyline = { version = "8.0.0", default-features = false }
rustyline-derive = "0.4.0"
semver-parser = "0.10.2"
serde = { version = "1.0.125", features = ["derive"] }
shell-escape = "0.1.5"
sourcemap = "6.0.1"
swc_bundler = "0.32.0"
swc_common = { version = "0.10.15", features = ["sourcemap"] }
swc_ecmascript = { version = "0.31.0", features = ["codegen", "dep_graph", "parser", "proposal", "react", "transforms", "typescript", "visit"] }
tempfile = "3.2.0"
termcolor = "1.1.2"
text-size = "1.1.0"
tokio = { version = "1.4.0", features = ["full"] }
tokio-rustls = "0.22.0"
uuid = { version = "0.8.2", features = ["v4"] }
walkdir = "2.3.2"

[target.'cfg(windows)'.dependencies]
fwdansi = "1.1.0"
winapi = { version = "0.3.9", features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }

[dev-dependencies]
# Used in benchmark
chrono = "0.4.19"
os_pipe = "0.9.2"
test_util = { path = "../test_util" }
tower-test = "0.4.0"
trust-dns-server = "0.20.1"
trust-dns-client = "0.20.1"

[target.'cfg(unix)'.dev-dependencies]
exec = "0.3.1" # Used in test_raw_tty
nix = "0.20.0"

[package.metadata.winres]
# This section defines the metadata that appears in the deno.exe PE header.
OriginalFilename = "deno.exe"
LegalCopyright = "© Deno contributors & Deno Land Inc. MIT licensed."
ProductName = "Deno"
FileDescription = "Deno: A secure runtime for JavaScript and TypeScript"
