# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "1.12.0"
license = "MIT"
authors = ["the Deno authors"]
edition = "2018"
description = "Provides the deno executable"
repository = "https://github.com/denoland/deno"
default-run = "deno"

[[bin]]
name = "deno"
path = "main.rs"

[[bench]]
name = "deno_bench"
harness = false
path = "./bench/main.rs"

[build-dependencies]
deno_broadcast_channel = { version = "0.5.0", path = "../extensions/broadcast_channel" }
deno_console = { version = "0.11.0", path = "../extensions/console" }
deno_core = { version = "0.93.0", path = "../core" }
deno_crypto = { version = "0.25.0", path = "../extensions/crypto" }
deno_fetch = { version = "0.33.0", path = "../extensions/fetch" }
deno_http = { version = "0.2.0", path = "../extensions/http" }
deno_net = { version = "0.2.0", path = "../extensions/net" }
deno_timers = { version = "0.9.0", path = "../extensions/timers" }
deno_url = { version = "0.11.0", path = "../extensions/url" }
deno_web = { version = "0.42.0", path = "../extensions/web" }
deno_webgpu = { version = "0.12.0", path = "../extensions/webgpu" }
deno_webidl = { version = "0.11.0", path = "../extensions/webidl" }
deno_websocket = { version = "0.16.0", path = "../extensions/websocket" }
deno_webstorage = { version = "0.6.0", path = "../extensions/webstorage" }
regex = "1.4.3"
serde = { version = "1.0.125", features = ["derive"] }

[target.'cfg(windows)'.build-dependencies]
winapi = "0.3.9"
winres = "0.1.11"

[dependencies]
deno_core = { version = "0.93.0", path = "../core" }
deno_doc = "0.8.0"
deno_lint = "0.10.0"
deno_runtime = { version = "0.19.0", path = "../runtime" }

atty = "0.2.14"
base64 = "0.13.0"
byteorder = "1.4.3"
clap = "2.33.3"
data-url = "0.1.0"
dissimilar = "1.0.2"
dprint-plugin-json = "0.12.1"
dprint-plugin-markdown = "0.9.2"
dprint-plugin-typescript = "0.48.0"
encoding_rs = "0.8.28"
env_logger = "0.8.4"
fancy-regex = "0.5.0"
filetime = "0.2.14"
http = "0.2.4"
# TODO(lucacasonato): unlock when https://github.com/tkaitchuck/aHash/issues/95 is resolved
indexmap = { version = "=1.6.2", features = ["serde"] } 
jsonc-parser = { version = "0.17.0", features = ["serde"] }
lazy_static = "1.4.0"
libc = "0.2.98"
log = { version = "0.4.14", features = ["serde"] }
lspower = "1.1.0"
notify = "5.0.0-pre.10"
num_cpus = "1.13.0"
percent-encoding = "2.1.0"
pin-project = "1.0.7"
regex = "1.4.3"
rand = { version = "0.8.4", features = [ "small_rng" ] }
ring = "0.16.20"
rustyline = { version = "8.2.0", default-features = false }
rustyline-derive = "0.4.0"
semver-parser = "0.10.2"
serde = { version = "1.0.126", features = ["derive"] }
shell-escape = "0.1.5"
sourcemap = "6.0.1"
swc_bundler = "0.45.0"
swc_common = { version = "0.10.23", features = ["sourcemap"] }
swc_ecmascript = { version = "0.45.0", features = ["codegen", "dep_graph", "parser", "proposal", "react", "transforms", "typescript", "visit"] }
tempfile = "3.2.0"
termcolor = "1.1.2"
text-size = "1.1.0"
tokio = { version = "1.8.1", features = ["full"] }
tokio-rustls = "0.22.0"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
walkdir = "2.3.2"

[target.'cfg(windows)'.dependencies]
fwdansi = "1.1.0"
winapi = { version = "0.3.9", features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }

[dev-dependencies]
# Used in benchmark
chrono = "0.4.19"
os_pipe = "0.9.2"
test_util = { path = "../test_util" }
tower-test = "0.4.0"
trust-dns-server = "0.20.3"
trust-dns-client = "0.20.3"

[target.'cfg(unix)'.dev-dependencies]
exec = "0.3.1" # Used in test_raw_tty
nix = "0.20.0"

[package.metadata.winres]
# This section defines the metadata that appears in the deno.exe PE header.
OriginalFilename = "deno.exe"
LegalCopyright = "© Deno contributors & Deno Land Inc. MIT licensed."
ProductName = "Deno"
FileDescription = "Deno: A secure runtime for JavaScript and TypeScript"
