# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "1.22.3"
authors = ["the Deno authors"]
default-run = "deno"
edition = "2021"
license = "MIT"
repository = "https://github.com/denoland/deno"
description = "Provides the deno executable"

[[bin]]
name = "deno"
path = "main.rs"

[[bench]]
name = "deno_bench"
harness = false
path = "./bench/main.rs"

[[bench]]
name = "lsp_bench_standalone"
harness = false
path = "./bench/lsp_bench_standalone.rs"

[build-dependencies]
deno_broadcast_channel = { version = "0.50.0", path = "../ext/broadcast_channel" }
deno_console = { version = "0.56.0", path = "../ext/console" }
deno_core = { version = "0.138.0", path = "../core" }
deno_crypto = { version = "0.70.0", path = "../ext/crypto" }
deno_fetch = { version = "0.79.0", path = "../ext/fetch" }
deno_net = { version = "0.48.0", path = "../ext/net" }
deno_url = { version = "0.56.0", path = "../ext/url" }
deno_web = { version = "0.87.0", path = "../ext/web" }
deno_webgpu = { version = "0.57.0", path = "../ext/webgpu" }
deno_websocket = { version = "0.61.0", path = "../ext/websocket" }
deno_webstorage = { version = "0.51.0", path = "../ext/webstorage" }
regex = "=1.5.6"
serde = { version = "=1.0.136", features = ["derive"] }
zstd = '=0.11.1'

[target.'cfg(windows)'.build-dependencies]
winapi = "=0.3.9"
winres = "=0.1.12"

[dependencies]
deno_ast = { version = "0.15.0", features = ["bundler", "cjs", "codegen", "dep_graph", "module_specifier", "proposal", "react", "sourcemap", "transforms", "transpiling", "typescript", "view", "visit"] }
deno_core = { version = "0.138.0", path = "../core" }
deno_doc = "0.35.0"
deno_emit = "0.2.0"
deno_graph = "0.27.0"
deno_lint = { version = "0.30.0", features = ["docs"] }
deno_runtime = { version = "0.64.0", path = "../runtime" }
deno_task_shell = "0.4.0"

atty = "=0.2.14"
base64 = "=0.13.0"
cache_control = "=0.2.0"
chrono = "=0.4.19"
clap = "=3.1.12"
clap_complete = "=3.1.2"
clap_complete_fig = "=3.1.5"
data-url = "=0.1.1"
dissimilar = "=1.0.3"
dprint-plugin-json = "=0.15.3"
dprint-plugin-markdown = "=0.13.3"
dprint-plugin-typescript = "=0.69.1"
encoding_rs = "=0.8.31"
env_logger = "=0.9.0"
eszip = "=0.20.0"
fancy-regex = "=0.9.0"
http = "=0.2.6"
import_map = "=0.11.0"
indexmap = "1.8.1"
jsonc-parser = { version = "=0.19.0", features = ["serde"] }
libc = "=0.2.126"
log = { version = "=0.4.17", features = ["serde"] }
mitata = '=0.0.7'
node_resolver = "=0.1.1"
notify = "=5.0.0-pre.15"
once_cell = "=1.12.0"
os_pipe = "=1.0.1"
percent-encoding = "=2.1.0"
pin-project = "=1.0.10"
rand = { version = "=0.8.5", features = ["small_rng"] }
regex = "=1.5.6"
ring = "=0.16.20"
rustyline = { version = "=9.1.2", default-features = false }
rustyline-derive = "=0.6.0"
secure_tempfile = { version = "=3.3.0", package = "tempfile" } # different name to discourage use in tests
semver-parser = "=0.10.2"
serde = { version = "=1.0.136", features = ["derive"] }
serde_repr = "=0.1.8"
shell-escape = "=0.1.5"
# temporary pins because swc did a broken publish
swc_common = "=0.18.5"
swc_ecma_codegen = "=0.108.2"
swc_ecma_codegen_macros = "=0.7.0"
swc_ecma_loader = "=0.30.1"
swc_ecma_parser = "=0.104.0"
swc_ecma_transforms_base = "=0.85.0"
swc_ecma_transforms_typescript = "=0.117.0"
swc_ecma_utils = "=0.85.0"
text-size = "=1.1.0"
text_lines = "=0.4.1"
tokio = { version = "=1.19", features = ["full"] }
tokio-util = "=0.7.2"
tower-lsp = "=0.17.0"
twox-hash = "=1.6.2"
typed-arena = "2.0.1"
uuid = { version = "=1.0.0", features = ["v4", "serde"] }
walkdir = "=2.3.2"
zstd = '=0.11.1'

[target.'cfg(windows)'.dependencies]
fwdansi = "=1.1.0"
winapi = { version = "=0.3.9", features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }

[dev-dependencies]
deno_bench_util = { version = "0.50.0", path = "../bench_util" }
flaky_test = "=0.1.0"
os_pipe = "=1.0.1"
pretty_assertions = "=1.2.1"
test_util = { path = "../test_util" }
trust-dns-client = "=0.21.2"
trust-dns-server = "=0.21.2"

[target.'cfg(unix)'.dev-dependencies]
nix = "=0.23.0"

[package.metadata.winres]
# This section defines the metadata that appears in the deno.exe PE header.
OriginalFilename = "deno.exe"
LegalCopyright = "© Deno contributors & Deno Land Inc. MIT licensed."
ProductName = "Deno"
FileDescription = "Deno: A secure runtime for JavaScript and TypeScript"
