# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "1.0.3"
license = "MIT"
authors = ["the Deno authors"]
edition = "2018"
description = "Provides the deno executable"
repository = "https://github.com/denoland/deno"
default-run = "deno"

[[bin]]
name = "deno"
path = "main.rs"

[build-dependencies]
deno_core = { path = "../core", version = "0.46.0" }
deno_typescript = { path = "../deno_typescript", version = "0.46.0" }

[dependencies]
deno_core = { path = "../core", version = "0.46.0" }
deno_typescript = { path = "../deno_typescript", version = "0.46.0" }

atty = "0.2.14"
base64 = "0.12.1"
bytes = "0.5.4"
byteorder = "1.3.4"
clap = "2.33.1"
dirs = "2.0.2"
dlopen = "0.1.8"
dprint-plugin-typescript = "0.19.0"
futures = { version = "0.3.5", features = ["compat", "io-compat"] }
glob = "0.3.0"
http = "0.2.1"
indexmap = "1.3.2"
lazy_static = "1.4.0"
libc = "0.2.71"
log = "0.4.8"
notify = "5.0.0-pre.2"
rand = "0.7.3"
regex = "1.3.7"
reqwest = { version = "0.10.4", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli"] }
ring = "0.16.13"
rustyline = "6.1.2"
serde = { version = "1.0.110", features = ["derive"] }
serde_derive = "1.0.110"
serde_json = { version = "1.0.53", features = [ "preserve_order" ] }
sys-info = "0.6.1"
sourcemap = "5.0.0"
tempfile = "3.1.0"
termcolor = "1.1.0"
tokio = { version = "0.2.21", features = ["rt-core", "tcp", "udp", "uds", "process", "fs", "blocking", "sync", "io-std", "macros", "time"] }
tokio-rustls = "0.13.1"
url = "2.1.1"
utime = "0.3.0"
webpki = "0.21.2"
webpki-roots = "0.19.0"
walkdir = "2.3.1"
warp = "0.2.3"
semver-parser = "0.9.0"
uuid = { version = "0.8.1", features = ["v4"] }
swc_ecma_visit = "0.5.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
fwdansi = "1.1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.17.0"

[dev-dependencies]
os_pipe = "0.9.2"
# Used for testing inspector. Keep in-sync with warp.
tokio-tungstenite = { version = "0.10.1", features = ["connect"] }

[target.'cfg(unix)'.dev-dependencies]
pty = "0.2.2"
