# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "1.25.1"
authors = ["the Deno authors"]
default-run = "deno"
edition = "2021"
license = "MIT"
repository = "https://github.com/denoland/deno"
description = "Provides the deno executable"

[[bin]]
name = "deno"
path = "main.rs"

[[bench]]
name = "deno_bench"
harness = false
path = "./bench/main.rs"

[[bench]]
name = "lsp_bench_standalone"
harness = false
path = "./bench/lsp_bench_standalone.rs"

[build-dependencies]
deno_broadcast_channel = { version = "0.61.0", path = "../ext/broadcast_channel" }
deno_console = { version = "0.67.0", path = "../ext/console" }
deno_core = { version = "0.149.0", path = "../core" }
deno_crypto = { version = "0.81.0", path = "../ext/crypto" }
deno_fetch = { version = "0.90.0", path = "../ext/fetch" }
deno_net = { version = "0.59.0", path = "../ext/net" }
deno_node = { version = "0.4.0", path = "../ext/node" }
deno_url = { version = "0.67.0", path = "../ext/url" }
deno_web = { version = "0.98.0", path = "../ext/web" }
deno_webgpu = { version = "0.68.0", path = "../ext/webgpu" }
deno_websocket = { version = "0.72.0", path = "../ext/websocket" }
deno_webstorage = { version = "0.62.0", path = "../ext/webstorage" }
regex = "=1.6.0"
serde = { version = "=1.0.144", features = ["derive"] }
zstd = '=0.11.1'

[target.'cfg(windows)'.build-dependencies]
winapi = "=0.3.9"
winres = "=0.1.12"

[dependencies]
deno_ast = { version = "0.19.0", features = ["bundler", "cjs", "codegen", "dep_graph", "module_specifier", "proposal", "react", "sourcemap", "transforms", "transpiling", "typescript", "view", "visit"] }
deno_core = { version = "0.149.0", path = "../core" }
deno_doc = "0.45.0"
deno_emit = "0.9.0"
deno_graph = "0.34.0"
deno_lint = { version = "0.33.0", features = ["docs"] }
deno_runtime = { version = "0.75.0", path = "../runtime" }
deno_task_shell = "0.5.2"

atty = "=0.2.14"
base64 = "=0.13.0"
cache_control = "=0.2.0"
chrono = "=0.4.19"
clap = "=3.1.12"
clap_complete = "=3.1.2"
clap_complete_fig = "=3.1.5"
data-url = "=0.1.1"
dissimilar = "=1.0.3"
dprint-plugin-json = "=0.15.6"
dprint-plugin-markdown = "=0.14.1"
dprint-plugin-typescript = "=0.73.1"
encoding_rs = "=0.8.31"
env_logger = "=0.9.0"
eszip = "=0.27.0"
fancy-regex = "=0.10.0"
flate2 = "=1.0.24"
http = "=0.2.6"
import_map = "=0.12.1"
indexmap = "1.8.1"
jsonc-parser = { version = "=0.21.0", features = ["serde"] }
libc = "=0.2.126"
log = { version = "=0.4.17", features = ["serde"] }
mitata = "=0.0.7"
monch = "=0.2.0"
notify = "=5.0.0-pre.15"
once_cell = "=1.12.0"
os_pipe = "=1.0.1"
path-clean = "=0.1.0"
percent-encoding = "=2.2.0"
pin-project = "1.0.11" # don't pin because they yank crates from cargo
rand = { version = "=0.8.5", features = ["small_rng"] }
regex = "=1.6.0"
ring = "=0.16.20"
rustyline = { version = "=10.0.0", default-features = false, features = ["custom-bindings"] }
rustyline-derive = "=0.7.0"
secure_tempfile = { version = "=3.3.0", package = "tempfile" } # different name to discourage use in tests
semver = "=1.0.13"
serde = { version = "=1.0.144", features = ["derive"] }
serde_repr = "=0.1.8"
shell-escape = "=0.1.5"
tar = "=0.4.38"
text-size = "=1.1.0"
text_lines = "=0.6.0"
tokio = { version = "=1.19", features = ["full"] }
tokio-util = "=0.7.2"
tower-lsp = "=0.17.0"
twox-hash = "=1.6.2"
typed-arena = "2.0.1"
uuid = { version = "=1.0.0", features = ["v4", "serde"] }
walkdir = "=2.3.2"
zstd = '=0.11.1'

[target.'cfg(windows)'.dependencies]
fwdansi = "=1.1.0"
winapi = { version = "=0.3.9", features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }

[dev-dependencies]
csv = "1.1.6"
deno_bench_util = { version = "0.61.0", path = "../bench_util" }
dotenv = "0.15.0"
flaky_test = "=0.1.0"
google-storage1 = "3.1.0"
once_cell = "=1.12.0"
os_pipe = "=1.0.1"
pretty_assertions = "=1.2.1"
test_util = { path = "../test_util" }
trust-dns-client = "=0.21.2"
trust-dns-server = "=0.21.2"

[target.'cfg(unix)'.dev-dependencies]
nix = "=0.24.2"

[package.metadata.winres]
# This section defines the metadata that appears in the deno.exe PE header.
OriginalFilename = "deno.exe"
LegalCopyright = "© Deno contributors & Deno Land Inc. MIT licensed."
ProductName = "Deno"
FileDescription = "Deno: A secure runtime for JavaScript and TypeScript"
