# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "0.31.0"
license = "MIT"
authors = ["the Deno authors"]
edition = "2018"
description = "Provides the deno executable"
repository = "https://github.com/denoland/deno"
default-run = "deno"

[lib]
name = "deno"
path = "lib.rs"

[[bin]]
name = "deno"
path = "main.rs"

[build-dependencies]
deno_core = { path = "../core", version = "0.31.0" }
deno_typescript = { path = "../deno_typescript", version = "0.31.0" }

[dependencies]
deno_core = { path = "../core", version = "0.31.0" }
deno_typescript = { path = "../deno_typescript", version = "0.31.0" }

ansi_term = "0.11.0"
atty = "0.2.13"
base64 = "0.11.0"
bytes = "0.5.3"
byteorder = "1.3.2"
brotli2 = "0.3.2"
clap = "2.33.0"
dirs = "2.0.2"
dlopen = "0.1.8"
dprint-plugin-typescript = "0.3.0-alpha.4"
futures = { version = "0.3.1", features = [ "compat", "io-compat" ] }
glob = "0.3.0"
http = "0.2.0"
indexmap = "1.3.0"
lazy_static = "1.4.0"
libc = "0.2.66"
log = "0.4.8"
rand = "0.7.2"
regex = "1.3.1"
remove_dir_all = "0.5.2"
reqwest = { version = "0.10.1", default-features = false, features = ["rustls-tls", "stream", "gzip"] }
ring = "0.16.9"
rustyline = "5.0.6"
serde = { version = "1.0.104", features = ["derive"] }
serde_derive = "1.0.104"
serde_json = { version = "1.0.44", features = [ "preserve_order" ] }
source-map-mappings = "0.5.0"
sys-info = "0.5.8"
tempfile = "3.1.0"
termcolor = "1.0.5"
tokio = { version = "0.2.9", features = ["full"] }
tokio-rustls = "0.12.1"
url = "2.1.0"
utime = "0.2.1"
webpki = "0.21.0"
webpki-roots = "0.17.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
fwdansi = "1.1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.14.1"

[dev-dependencies]
os_pipe = "0.9.1"
