# Copyright 2018-2019 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_cli"
version = "0.19.0"
license = "MIT"
authors = ["the Deno authors"]
edition = "2018"
description = "Provides the deno executable"
repository = "https://github.com/denoland/deno"
default-run = "deno"

[lib]
name = "deno_cli"
path = "lib.rs"

[[bin]]
name = "deno"
path = "main.rs"

[dependencies]
deno = { path = "../core", version = "0.19.0" }
deno_cli_snapshots = { path = "../js", version = "0.19.0" }
deno_typescript = { path = "../deno_typescript", version = "0.19.0" }

ansi_term = "0.12.1"
atty = "0.2.13"
clap = "2.33.0"
dirs = "2.0.2"
futures = "0.1.29"
http = "0.1.18"
hyper = "0.12.34"
hyper-rustls = "0.17.1"
indexmap = "1.2.0"
lazy_static = "1.4.0"
libc = "0.2.62"
log = "0.4.8"
rand = "0.7.0"
regex = "1.3.1"
remove_dir_all = "0.5.2"
reqwest = { version = "0.9.20", default-features = false, features = ["rustls-tls"] }
ring = "0.16.9"
rustyline = "5.0.2"
serde = { version = "1.0.100", features = ["derive"] }
serde_derive = "1.0.100"
serde_json = { version = "1.0.40", features = [ "preserve_order" ] }
source-map-mappings = "0.5.0"
tempfile = "3.1.0"
termcolor = "1.0.5"
tokio = "0.1.22"
tokio-executor = "0.1.8"
tokio-fs = "0.1.6"
tokio-io = "0.1.12"
tokio-process = "0.2.4"
tokio-rustls = "0.10.0"
tokio-threadpool = "0.1.15"
url = "1.7.2"
utime = "0.2.1"
webpki = "0.21.0"
webpki-roots = "0.17.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
fwdansi = "1.0.1"

[target.'cfg(unix)'.dependencies]
nix = "0.14.1"

[dev-dependencies]
os_pipe = "0.8.2"
