[package]
name = "test_util"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
publish = false

[[bin]]
name = "test_server"
path = "src/test_server.rs"

[dependencies]
tokio = { version = "0.2.21", features = ["full"] }
futures = { version = "0.3.5", features = ["compat", "io-compat"] }
bytes = "0.5.5"
lazy_static = "1.4.0"
os_pipe = "0.9.2"
regex = "1.3.9"
tempfile = "3.1.0"
warp = { version = "0.2.3", features = ["tls"] }
