# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "test_util"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
publish = false

[[bin]]
name = "test_server"
path = "src/test_server.rs"

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
futures = "0.3.8"
bytes = "0.5.6"
lazy_static = "1.4.0"
os_pipe = "0.9.2"
regex = "1.3.9"
tempfile = "3.1.0"
hyper = "0.13"
tokio-tungstenite = "0.11"
tokio-rustls = "0.14"

[target.'cfg(unix)'.dependencies]
pty = "0.2.2"
