# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "test_util"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
publish = false

[[bin]]
name = "test_server"
path = "src/test_server.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
bytes = "1"
lazy_static = "1.4.0"
os_pipe = "0.9"
regex = "1.3.9"
tempfile = "3.1.0"
hyper = { version = "0.14.2", features = ["server", "http1", "runtime"] }
tokio-tungstenite = "0.13"
tokio-rustls = "0.22"
async-stream = "0.3.0"

[target.'cfg(unix)'.dependencies]
pty = "0.2.2"
