# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "test_util"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
publish = false

[[bin]]
name = "test_server"
path = "src/test_server.rs"

[dependencies]
async-stream = "0.3.0"
bytes = "1.0.1"
futures = "0.3.12"
hyper = { version = "0.14.4", features = ["server", "http1", "runtime"] }
lazy_static = "1.4.0"
os_pipe = "0.9.2"
regex = "1.4.3"
serde = { version = "1.0.123", features = ["derive"] }
tempfile = "3.2.0"
tokio = { version = "1.2.0", features = ["full"] }
tokio-rustls = "0.22.0"
tokio-tungstenite = "0.13.0"

[target.'cfg(unix)'.dependencies]
pty = "0.2.2"
