# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_websocket"
version = "0.89.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of WebSocket API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
deno_tls.workspace = true
http.workspace = true
hyper.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
