# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_websocket"
version = "0.35.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Implementation of WebSocket API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.112.0", path = "../../core" }
deno_tls = { version = "0.17.0", path = "../tls" }
http = "0.2.4"
hyper = { version = "0.14.12" }
serde = { version = "1.0.129", features = ["derive"] }
tokio = { version = "1.10.1", features = ["full"] }
tokio-rustls = "0.23.0"
tokio-tungstenite = { version = "0.16.0", features = ["rustls-tls-webpki-roots"] }
