# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.
[package]
name = "deno_core"
version = "0.98.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "A secure JavaScript/TypeScript runtime built with V8, Rust, and Tokio"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0.41"
futures = "0.3.15"
# TODO(lucacasonato): unlock when https://github.com/tkaitchuck/aHash/issues/95 is resolved
indexmap = "=1.6.2"
lazy_static = "1.4.0"
libc = "0.2.98"
log = "0.4.14"
parking_lot = "0.11.1"
pin-project = "1.0.7"
rusty_v8 = "0.26.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
serde_v8 = { version = "0.9.3" }
url = { version = "2.2.2", features = ["serde"] }

[[example]]
name = "http_bench_json_ops"
path = "examples/http_bench_json_ops.rs"

# These dependencies are only used for the 'http_bench_*_ops' examples.
[dev-dependencies]
tokio = { version = "1.8.1", features = ["full"] }
