# Copyright 2018-2019 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "0.19.0"
edition = "2018"
description = "A secure JavaScript/TypeScript runtime built with V8, Rust, and Tokio"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
futures = "0.1.29"
lazy_static = "1.4.0"
libc = "0.2.62"
log = "0.4.8"
serde_json = "1.0.40"
url = "1.7.2"

[[example]]
name = "deno_core_http_bench"
path = "examples/http_bench.rs"

# tokio is only used for deno_core_http_bench
[dev_dependencies]
tokio = "0.1.18"
