# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.
[package]
name = "deno_core"
version = "0.104.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "A modern JavaScript/TypeScript runtime built with V8, Rust, and Tokio"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0.43"
futures = "0.3.16"
# TODO(lucacasonato): unlock when https://github.com/tkaitchuck/aHash/issues/95 is resolved
indexmap = "=1.6.2"
lazy_static = "1.4.0"
log = "0.4.14"
parking_lot = "0.11.1"
pin-project = "1.0.7"
rusty_v8 = "0.32.0"
serde = { version = "1.0.129", features = ["derive"] }
serde_json = { version = "1.0.66", features = ["preserve_order"] }
serde_v8 = "0.15.0"
url = { version = "2.2.2", features = ["serde"] }

[[example]]
name = "http_bench_json_ops"
path = "examples/http_bench_json_ops.rs"

# These dependencies are only used for the 'http_bench_*_ops' examples.
[dev-dependencies]
tokio = { version = "1.10.1", features = ["full"] }
