# Copyright 2018-2019 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "0.3.5"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
futures = "0.1.25"
lazy_static = "1.3.0"
libc = "0.2.51"
log = "0.4.6"
serde_json = "1.0.39"
