# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.
[package]
name = "deno_core"
version = "0.77.1"
edition = "2018"
description = "A secure JavaScript/TypeScript runtime built with V8, Rust, and Tokio"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0.38"
futures = "0.3.12"
indexmap = "1.6.1"
lazy_static = "1.4.0"
libc = "0.2.82"
log = "0.4.13"
pin-project = "1.0.4"
rusty_v8 = "0.16.0"
serde = { version = "1.0.121", features = ["derive"] }
serde_json = { version = "1.0.61", features = ["preserve_order"] }
smallvec = "1.6.1"
url = { version = "2.2.0", features = ["serde"] }

[[example]]
name = "http_bench_bin_ops"
path = "examples/http_bench_bin_ops.rs"

[[example]]
name = "http_bench_json_ops"
path = "examples/http_bench_json_ops.rs"

# These dependencies are only used for the 'http_bench_*_ops' examples.
[dev-dependencies]
tokio = { version = "1.1.0", features = ["full"] }
