# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_core"
version = "0.30.1"
edition = "2018"
description = "A secure JavaScript/TypeScript runtime built with V8, Rust, and Tokio"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
downcast-rs = "1.1.1"
futures = { version = "0.3.1", features = [ "thread-pool", "compat" ] }
lazy_static = "1.4.0"
libc = "0.2.66"
log = "0.4.8"
serde_json = "1.0.44"
url = "2.1.0"
rusty_v8 = "0.1.1"

[[example]]
name = "deno_core_http_bench"
path = "examples/http_bench.rs"

# tokio is only used for deno_core_http_bench
[dev_dependencies]
tokio = { version = "0.2", features = ["full"] }
num_cpus = "1.11.1"
