# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fetch"
version = "0.87.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Fetch API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
bytes = "1.1.0"
data-url = "0.1.1"
deno_core = { version = "0.146.0", path = "../../core" }
deno_tls = { version = "0.51.0", path = "../tls" }
dyn-clone = "1"
http = "0.2.6"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli"] }
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17", features = ["full"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.7.1", features = ["io"] }
