# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_flash"
version = "0.2.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Fast HTTP/1 server implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { path = "../../core", version = "0.148.0" }
deno_tls = { version = "0.53.0", path = "../tls" }
# For HTTP/2 and websocket upgrades
deno_websocket = { version = "0.71.0", path = "../websocket" }
http = "0.2.6"
httparse = "1.7"
libc = "0.2"
log = "0.4.17"
mio = { version = "0.8.1", features = ["os-poll", "net"] }
rustls = { version = "0.20" }
rustls-pemfile = { version = "0.2.1" }
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.19", features = ["full"] }
