# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webstorage"
version = "0.14.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Implementation of WebStorage API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.101.0", path = "../../core" }
deno_web = { version = "0.50.0", path = "../web" }
rusqlite = { version = "0.25.3", features = ["unlock_notify", "bundled"] }
serde = { version = "1.0.129", features = ["derive"] }
