# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.
[package]
name = "serde_v8"
version = "0.60.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Rust to V8 serialization and deserialization"

[lib]
path = "lib.rs"

[dependencies]
bytes = "=1.2.1"
derive_more = "0.99.17"
serde = { version = "1.0.136", features = ["derive"] }
serde_bytes = "0.11"
smallvec = { version = "1.8", features = ["union"] }
v8 = { version = "0.49.0", default-features = false }

[dev-dependencies]
bencher = "0.1"
serde_json = "1.0.64"

[[example]]
name = "basic"

[[bench]]
name = "de"
harness = false

[[bench]]
name = "ser"
harness = false
