[package]
name = "serde_v8"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
description = "Rust to V8 serialization and deserialization"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
rusty_v8 = "0.21.0"

[dev-dependencies]
serde_json = "1.0.62"
bencher = "0.1"

[[example]]
name = "basic"

[[bench]]
name = "de"
harness = false

[[bench]]
name = "ser"
harness = false
