# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webgpu"
version = "0.80.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository = "https://github.com/gfx-rs/wgpu"
description = "WebGPU implementation for Deno"

[dependencies]
deno_core.workspace = true
serde.workspace = true
tokio.workspace = true
wgpu-core = { version = "0.13", features = ["trace", "replay", "serde"] }
wgpu-types = { version = "0.13", features = ["trace", "replay", "serde"] }
