# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webgpu"
version = "0.68.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/gfx-rs/wgpu"
description = "WebGPU implementation for Deno"

[dependencies]
deno_core = { version = "0.149.0", path = "../../core" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.17", features = ["full"] }
wgpu-core = { version = "0.13", features = ["trace", "replay", "serde"] }
wgpu-types = { version = "0.13", features = ["trace", "replay", "serde"] }
