# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_timers"
version = "0.9.0"
edition = "2018"
description = "Timers API implementation for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.93.0", path = "../../core" }
tokio = { version = "1.8.1", features = ["full"] }

[dev-dependencies]
deno_bench_util = { version = "0.5.0", path = "../../bench_util" }
deno_url = { version = "0.11.0", path = "../url" }
deno_web = { version = "0.42.0", path = "../web" }
deno_webidl = { version = "0.11.0", path = "../webidl" }

[[bench]]
name = "timers_ops"
harness = false
