# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_web"
version = "0.89.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Collection of Web APIs"

[lib]
path = "lib.rs"

[dependencies]
async-trait = "0.1.51"
base64 = "0.13.0"
deno_core = { version = "0.140.0", path = "../../core" }
encoding_rs = "0.8.31"
flate2 = "1"
serde = "1.0.136"
tokio = { version = "1.17", features = ["full"] }
uuid = { version = "1.0.0", features = ["v4", "serde"] }

[dev-dependencies]
deno_bench_util = { version = "0.52.0", path = "../../bench_util" }
deno_url = { version = "0.58.0", path = "../url" }
deno_webidl = { version = "0.58.0", path = "../webidl" }

[[bench]]
name = "encoding"
harness = false

[[bench]]
name = "timers_ops"
harness = false
