name: build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-16.04]
        kind: ['test', 'test_std', 'bench', 'lint']
        exclude:
          - os: windows-2016
            kind: 'bench'
          - os: windows-2016
            kind: 'lint'
          - os: macOS-10.14
            kind: 'bench'
          - os: macOS-10.14
            kind: 'lint'
    steps:
      - name: Configure git
        run: git config --global core.symlinks true

      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: "1.38.0"

      - name: Install clippy and rustfmt
        if: matrix.kind == 'lint'
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: "2.7.16"
          architecture: x64

      - name: Environment (common)
        run: |
          echo ::set-env name=GH_ACTIONS::1
          echo ::set-env name=RUSTC_WRAPPER::sccache
          echo ::set-env name=DENO_BUILD_MODE::release

      - name: Environment (linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          echo ::add-path::`pwd`/prebuilt/linux64

      - name: Environment (mac)
        if: startsWith(matrix.os, 'macOS')
        run: |
          echo ::add-path::`pwd`/prebuilt/mac

      - name: Environment (windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          echo ::add-path::%cd%\prebuilt\win

      - name: Log versions
        run: |
          node -v
          python --version
          rustc --version
          cargo --version

      - name: Run setup.py
        run: python ./tools/setup.py

      - name: Start sccache
        env:
          AWS_ACCESS_KEY_ID: AKIAIVRN52PLDBP55LBQ
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SCCACHE_BUCKET: deno-sccache
          SCCACHE_IDLE_TIMEOUT: 0
        run: sccache --start-server

      - name: lint.py
        if: matrix.kind == 'lint'
        run: python ./tools/lint.py

      - name: test_format.py
        if: matrix.kind == 'lint'
        run: python ./tools/test_format.py

      - name: Clippy
        if: matrix.kind == 'lint'
        run: cargo clippy --all-targets --release --locked -- -D clippy::all

      - name: Build
        if: matrix.kind != 'lint'
        run: cargo build --release --locked --all-targets

      # TODO(ry) Remove this step, and move the following test to
      # cli/tests/std_tests.rs
      # TODO(ry) Remove the "cd std".
      - name: std test
        if: matrix.kind == 'test_std'
        run: |
          cd std
          "../target/release/deno" test -A

      - name: Test
        if: matrix.kind == 'test'
        run: cargo test --release --locked --all-targets

      - name: Run Benchmarks
        if: matrix.kind == 'bench'
        run: python ./tools/benchmark.py target/release

      - name: Post Benchmarks
        if: matrix.kind == 'bench' && github.ref == 'refs/heads/master' && github.repository == 'denoland/deno'
        env:
          DENOBOT_PAT: ${{ secrets.DENOBOT_PAT }}
        run: |
          git clone --depth 1 -b gh-pages https://${DENOBOT_PAT}@github.com/denoland/deno.git gh-pages
          python ./tools/build_benchmark_jsons.py
          cp -r website/* gh-pages/
          cd gh-pages
          git config user.email "propelml@gmail.com"
          git config user.name "denobot"
          git add .
          git commit --message "Update benchmarks"
          git push origin gh-pages

      - name: Worker info
        if: matrix.kind == 'bench'
        run: |
          cat /proc/cpuinfo
          cat /proc/meminfo

      - name: Pre-release (linux)
        if: startsWith(matrix.os, 'ubuntu') && matrix.kind != 'lint'
        run: gzip -c target/release/deno > target/release/deno_linux_x64.gz

      - name: Pre-release (mac)
        if: startsWith(matrix.os, 'macOS') && matrix.kind != 'lint'
        run: gzip -c target/release/deno > target/release/deno_osx_x64.gz

      - name: Pre-release (windows)
        if: startsWith(matrix.os, 'windows') && matrix.kind != 'lint'
        run: PowerShell -Command "& {Compress-Archive -CompressionLevel Optimal -Force -Path target/release/deno.exe -DestinationPath target/release/deno_win_x64.zip}"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.kind == 'test' && startsWith(github.ref, 'refs/tags/') && github.repository == 'denoland/deno'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/release/deno_win_x64.zip
            target/release/deno_linux_x64.gz
            target/release/deno_osx_x64.gz
          draft: true

      - name: Stop sccache
        run: sccache --stop-server
