name: version_bump

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: 'Kind of version bump'
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        required: true

jobs:
  build:
    name: version bump
    runs-on: ubuntu-20.04-xl
    timeout-minutes: 90

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DENOBOT_PAT }}
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.19.3

      - name: Run version bump
        run: |
          git remote add upstream https://github.com/denoland/deno
          ./tools/release/01_bump_crate_versions.ts --${{github.event.inputs.releaseKind}}

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.DENOBOT_PAT }}
          GH_WORKFLOW_ACTOR: ${{ github.actor }}
        run: |
          git config user.email "propelml@gmail.com"
          git config user.name "denobot"
          ./tools/release/02_create_pr.ts
