# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_webidl"
version = "0.2.1"
edition = "2018"
description = "WebIDL implementation for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.83.0", path = "../../core" }
